import assert from "node:assert/strict";
import path from "node:path";
import { before, describe, it } from "node:test";
import { fileURLToPath } from "node:url";
import { testAdmin, type AdminTester } from "zusantara/admin";

// Tests for the users admin panel (generated by zusantara make:admin), with an in-memory SQLite database.
process.env.DATABASE_URL = ":memory:";
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

describe("admin: Users", () => {
  let t: AdminTester;

  before(async () => {
    const { db } = await import("../src/app/db/index.js");
    const { migrateDatabase } = await import("zusantara/db");
    await migrateDatabase(db, path.join(ROOT, "drizzle"));
    t = testAdmin((await import("../src/app/admin/index.js")).admin);
  });

  it("list, form, and access", async () => {
    const admin = { role: "admin" };
    assert.equal((await t.get("/admin/users", admin)).status, 200);
    assert.equal((await t.get("/admin/users/new", admin)).status, 403);
    assert.equal((await t.get("/admin/users", { role: "guest" })).status, 403);
    assert.equal((await t.get("/admin/users")).status, 401);
  });
});
