import { defineResource, type GeneratedResource } from "zusantara/admin";
import { db } from "../db/index.js";
import { notes } from "../db/schema.js";

// zusantara:generated:begin admin-resource sha256=60c6d47ef90c
// Generated by `zusantara make:admin notes` from the database schema. Run that command again after the schema
// changes: only this block is updated. Change the display through `overrides` below, not here.
const generated: GeneratedResource = {
  name: "notes",
  label: "Notes",
  singular: "Note",
  titleField: "title",
  fields: [
    { name: "id", label: "ID", type: "number", form: false, sort: true },
    { name: "userId", label: "User", type: "relation", required: true, relation: { labelKey: "name" }, filter: true, sort: true },
    { name: "title", label: "Title", type: "text", required: true, search: true, sort: true },
    { name: "body", label: "Body", type: "textarea", list: false },
    { name: "createdAt", label: "Created", type: "datetime", form: false, sort: true, filter: true },
    { name: "updatedAt", label: "Updated", type: "datetime", form: false, sort: true },
  ],
};
// zusantara:generated:end admin-resource

export default defineResource({
  ...generated,
  table: notes,
  db,
  // Who may view, add, edit, and delete (role from ctx.state.user.role).
  access: { view: ["admin"], create: ["admin"], update: ["admin"], delete: ["admin"] },
  // Change fields without touching the block above, e.g. { price: { label: "Sale price" }, notes: { list: false } }.
  overrides: {},
});
