import { AdminError, defineResource, type GeneratedResource } from "zusantara/admin";
import { db } from "../db/index.js";
import { users } from "../db/schema.js";

// zusantara:generated:begin admin-resource sha256=31dabfa879e1
// Generated by `zusantara make:admin users` from the database schema. Run that command again after the schema
// changes: only this block is updated. Change the display through `overrides` below, not here.
const generated: GeneratedResource = {
  name: "users",
  label: "Users",
  singular: "User",
  titleField: "name",
  create: false,
  fields: [
    { name: "id", label: "ID", type: "number", form: false, sort: true },
    { name: "email", label: "Email", type: "email", required: true, search: true, sort: true },
    { name: "name", label: "Name", type: "text", required: true, search: true, sort: true },
    { name: "role", label: "Role", type: "enum", options: ["user", "admin"], filter: true, sort: true, inline: true },
    { name: "createdAt", label: "Created", type: "datetime", form: false, sort: true, filter: true },
  ],
};
// zusantara:generated:end admin-resource

export default defineResource({
  ...generated,
  table: users,
  db,
  // Who may view, add, edit, and delete (role from ctx.state.user.role).
  // New accounts sign up through the register page, and accounts are not deleted from the panel (their notes point at them).
  access: { view: ["admin"], update: ["admin"], delete: false },
  // Change fields without touching the block above, e.g. { price: { label: "Sale price" }, notes: { list: false } }.
  overrides: {},
  // Admins cannot remove their own admin role, so the panel never loses its last admin by accident.
  beforeSave(values, ctx, existing) {
    const me = ctx.state.user as { id?: number } | undefined;
    if (existing && existing.id === me?.id && values.role !== undefined && values.role !== "admin") throw new AdminError("You cannot remove your own admin role.", "role");
  },
});
